apiVersion: v1
kind: Plugin
metadata:
  author: TrendRadar
  name: push_queue
  repository: ''
  version: 1.0.0
  description:
    en_US: 'TrendRadar push queue processor - monitors .push_queue and sends via LangBot'
    zh_Hans: 'TrendRadar 推送队列处理器 - 监听队列目录，通过 LangBot 发送消息'
  label:
    en_US: PushQueue
    zh_Hans: 推送队列
spec:
  config: []
  components:
    EventListener:
      fromDirs:
        - path: components/event_listener
          maxDepth: 2
execution:
  python:
    path: main.py
    attr: PushQueuePlugin
